version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gestaoramais
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestaoramais
      MYSQL_USER: humberto
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    restart: always
